apiVersion: v1
kind: Secret
metadata:
    name: headlamp-app-secrets
    namespace: headlamp-system
type: Opaque
stringData:
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:i7R2m5OX/pvlj/um8lhfYJg5,iv:kq2oRRBR6p3P9QMsGdcww/3HEGejWE/CxAthWvcvlmk=,tag:4cNVlpHLENw+UoCMj8yzhg==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:UTd3XUgb6XWn6A4k5jQDGVmSyR6dDS+3Miso4cPuKRckkQ/oEkHkogFy6/w6s05k647cgvebzcVr2Lgntg392Q==,iv:XFJm3hsKLmJHyEyWhhuEL1JgfbFZdFePEwXjYVPYe3k=,tag:xBc8m6OKgcokPxU5cnyXAA==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTFlRQTJTTDJnNktVNGJG
            YTRGaXQ5dWpkeGEwZmM3VFZNc3ZucnFvcHk0Cmgxa3JNbWhTSzhBeGlTNXpQMHBU
            bnRUQ1ZuR3cyZkQ4MkVuYkI1YXYvN2MKLS0tIHZ3dXYvV2ZwekJqTFBuYS9yMG13
            YWVoSFZ2WkozZGRTV0NUOUpXZWRCTlkKaVhFy5X0t+PKbeyDB9zZOROTxAi30mSp
            t5WkipDrjQ3baMerKakbx5g1VU2feoBMwpOxB4bgojefCPAgOXlwgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T03:08:53Z"
    mac: ENC[AES256_GCM,data:V5OLAvIcjpjsfx4pQ+XrG3UcQmmYaUb+CDOUxtYjoDJG6mpghFZ7g1xQLc2PKS2zkvSAESApEJdDarzhLF4wEPsf8gRGLbO67Zv0FzBntyeyBoUH0l1QtBJjS1L7DIyDLn/sOokGYeaNJZ2L0Auml+KQb98HerOM+WNsux+F91M=,iv:I1d+/Uci40SGbRVSU16lYcX79zgazRJxpaesEp960+Y=,tag:OwgHs+gMwW0Htx36vFiqCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
