apiVersion: v1
kind: Secret
metadata:
    name: beetube-postgres-owner
    namespace: beetube
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:+WLo691Vqw==,iv:lX65MTNouikrfHNV4JO7ld3u96czJsTT504BzbVewFA=,tag:hJg3HHCO+57HbEYLSaLdHw==,type:str]
    password: ENC[AES256_GCM,data:fBh8a983e01GLNiALNBY,iv:EKuCejbVDpc3L2NygD/Q526ncT0V/aDuIZrAt9/GWsQ=,tag:M/PuiSgaAZjEYYtIccPY5A==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNnYrVTRXNDdWSWg0N0Ux
            R3M4WEFOMlVrY0l1eXhrbGN5MDFiUHFZb3cwCklVN28vbjFub0thMXA3emNIaTZ6
            SzFoZzZqQmRReWovUVowUnZiWTF4SzAKLS0tIFd5bFJuSDdrdWs3N1A5blJBRkZB
            QmRhNFdtQ1lSOExEbFk2bTBiY3BQb3cKhbBvA5ExiHhyprHyWCputqeAyE0FSKnR
            C9HBD/U3k0vOXTOtJvdUt8OGMJenP/YBc/7XgRkcx861yDsWqh43OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T17:09:25Z"
    mac: ENC[AES256_GCM,data:fm7KUP9KTwhsKbFQz/x6tHaDZRGp7OUGd+W54PN/GnJm3WbIHcSiktf3dTDpZR/Xs1Bw57dDpaofFOaKaBSWKJRWQ+EXnKKLrjcnckRCGh98jpIx5/qonKU1Ib1UcOVRfLDlE4bC8WCu3zHFdbo6iG2kGyTyRaUOBjasQMT3C7k=,iv:5yV6mSDjhHrf9FNDlwsnnsYFQJU91vApiyq3CrEiCaM=,tag:AEz19PojhDpPZn8xyoY0/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: beetube-app-secrets
    namespace: beetube
type: Opaque
stringData:
    YOUTUBE_API_KEY: ENC[AES256_GCM,data:po58YcU5N65M82t/bTple8UpDblw0S60tr2KFC5OpwWSHK468wWp,iv:jtzZSEnNK+3PsxeXZJwnq6YYvE/++fAaEbDhBLkMtw0=,tag:Q3FzYj4X8NJslBDz3yg6eg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:AMr3edYSkgQN4wZa/chh9qlF3cRw5O8sBBz+6Q8MYbkJzhqFzN8muJQqZj8CeGxqCNJV7XxJAp7tXkkek8A5OA==,iv:li7dyaU5waJCi5rYWS1iiBoOHAggB286OFxjCwCK6zU=,tag:luZNB+UZo3QdwsnJZOo48w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:2fc+Fk0j156VwOy40Zbto+cfiCtNSGzW1Ca5bYsRsLqg6BXLL7iVCZpa2zQZF21ea6wLM/bm+6SqI278xv4rU09B7Co/rWMlRgbEnrttnh2Antz9cdwI6KwMMgsjqe9W0X8tLENjahtUyRjO3iPD1WM=,iv:TyH8hhA46tm5LPC2fFvswsgPqNOHltdZb3G1lA966b8=,tag:/ihOZN9dtFWG8stMjhokag==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:YpHvlXedhMGZ9YXLN0Q7VdYG,iv:odHAs/eVwNSDvawikTK1/YO5kZxSLoRe038Q2Orx06g=,tag:urgBXnGFHlREBtvpxqgJ3Q==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:XqizN8n8gvXLfzzcEk8U0mHIRg7sqRQwd7A/Uq5elJDg+9SrHZyfxKaBWDlpm+2ldRthRMA4nHCMisDlpEmUXw==,iv:HOBXnGZS3Xdm42WxUlPRkVPKmHbwm7CkyD3yxKI22hM=,tag:Zix1Ylo4yO5Tx9sAwocqww==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNnYrVTRXNDdWSWg0N0Ux
            R3M4WEFOMlVrY0l1eXhrbGN5MDFiUHFZb3cwCklVN28vbjFub0thMXA3emNIaTZ6
            SzFoZzZqQmRReWovUVowUnZiWTF4SzAKLS0tIFd5bFJuSDdrdWs3N1A5blJBRkZB
            QmRhNFdtQ1lSOExEbFk2bTBiY3BQb3cKhbBvA5ExiHhyprHyWCputqeAyE0FSKnR
            C9HBD/U3k0vOXTOtJvdUt8OGMJenP/YBc/7XgRkcx861yDsWqh43OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T17:09:25Z"
    mac: ENC[AES256_GCM,data:fm7KUP9KTwhsKbFQz/x6tHaDZRGp7OUGd+W54PN/GnJm3WbIHcSiktf3dTDpZR/Xs1Bw57dDpaofFOaKaBSWKJRWQ+EXnKKLrjcnckRCGh98jpIx5/qonKU1Ib1UcOVRfLDlE4bC8WCu3zHFdbo6iG2kGyTyRaUOBjasQMT3C7k=,iv:5yV6mSDjhHrf9FNDlwsnnsYFQJU91vApiyq3CrEiCaM=,tag:AEz19PojhDpPZn8xyoY0/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
