apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared/homelab
  - external-dns/homelab
  - gateway/homelab
  - gateway-api/crds
  - metallb-bootstrap/homelab
  - metallb-config/homelab
  - traefik/homelab
