apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:hHH48pvCxidTcOnGya61OJDkTrT4qgTKDdZtD/I8Tc6z5pC07KJn5470u0KeCwdhJxhlVlw=,iv:gWvnRxh18bnq4mbnb99E772EzaZ1Dkh8KUlwnv9N1yw=,tag:OzrA9W6nvik4MWDSWuiZvQ==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUVp5OG1MN0kyalFtNDJZ
            MUNONGYzS3p3NzVtU1pYQ3BVdkxKblpPanpvCkVYVkk4dVJBRzlrRlgxbXQ4NnMy
            b3VtakZnUE44THh4NVQ3YXVaM1VVUlEKLS0tIEtGaWFGQnRsdFlwQ1dRRERXNUJD
            WkJoYWRYWGVSMXliemhWMytlWmVhODgKWazyHDHUk4hPr/KOaQPgdw4yriTY5Wyj
            2s04N+MJQb1nB1F2kaqXNkAK8nYhvD3CU8eg17Df3h/2YTaE2GpSYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T21:40:44Z"
    mac: ENC[AES256_GCM,data:zOFjQl0pDBuIX1wWR4nmeJ8omKaBFpHc9Pq+99oYsiSDrJjCTHkVxf7e0qbz3jekdjTtfcoZd3br3jTJtVi8HsfbflNls6cDZxv9evVz7xv7PZppQsLJ+Yfpm18+1wn/TvTQbPlYBPQFkwSGkj17jDMQ3nchqgfOb0E6tZkugS4=,iv:UTipVwNfXUgwcRyN/rp4IhVBZIE2PkstLnvyacMyECo=,tag:kJU34UgtQSuCQJ5EgxNfPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
