apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: external-dns
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:vCpAZmwMtAR3hNclj+Wccof4R3ofIneHv8aE1uEEiQS4MTsG6g0Q87bs4xKJn7p7Mrm3V44=,iv:6h8RvzcKNsDn4pApGmbRgCGJJUhrK1Iz39H5ugi+dVA=,tag:f5U7BSGlO6iqZ7sMGSjMaQ==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WnBTdEQwL3FHbXNGalBW
            OFdtY1U4L0R0MTFBNDZGZVNpMnhVL0U4MEZNCm5BNG9GVTFWZXF1M2dqcDdxZUlx
            UGw5bmtTNnFjVnVzeUdURWZGb1M2eXcKLS0tIDVZSkw4akxiYmhUWEZKWWxaU2Rs
            NXc1SllPMFNmREJobDd4cWRoR0I5NkUKQiGWnXgqNInMd41osHGHBDf75v3acdjB
            xG5nOBLBFYr1J1rWmPwpQKyKQDLv3hsSPamOfF3HwioP8MQ6fmE21w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T21:00:18Z"
    mac: ENC[AES256_GCM,data:P/rxsADnPdAl9+2IXBJongzmv05q0s0MXiub8qObCRU53r0tAvB9MwRu6u0Iq2bi8op/YjKGNejoaipqPO0aQ81XhuWQoH44xM7nwK1bnEaSW+VdHrwP9Wu4XqsFK2h0ZDtdncFPxCzO6kheH+06LNXDMTUggkOO+DINSFFEgPg=,iv:Pta1+njmUjjwDuo/Z1a8yQJY5+++1+3D9CtxuP7ZrL0=,tag:RLhmyHjiwCA5206ie9bsww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
