apiVersion: v1
kind: Secret
metadata:
    name: memos-postgres-owner
    namespace: memos
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:z3Xpugw=,iv:638U9+xbwQRnPgGvDD++zsik0L8ZmX3tvNj4Q6HVG80=,tag:LVrfbPXuhRpmfz3nuX5iBQ==,type:str]
    password: ENC[AES256_GCM,data:t8//UBn9bwTR6Rn4Bw==,iv:UVE2VpnjB+AgYkRemLiIFKXbi/sgXVGuRRGr9K+MwEQ=,tag:GbXTED0gO/6cjxZAIbdEYQ==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOXQvQmExamwvU1U1TXFJ
            YXI2RHlzV1ZoazZ1aEJ2czFpYUwwUWFqU1cwCkZ4TThWY3ltellhZTQzKzZQV2Ro
            RlV0S2hHL3JEUjhaR3lGMHJwUWphVVkKLS0tIHB0MWxYdENseDJoTFVRTXc4V0ll
            OEtlcngybUo1aEJGR3pEVGIrU2RaMHMKzNYlu4bbfqWx8yJ1nQhWJ+e83NduaLWQ
            d/5z/tyq9wjBQGkfp2iSYviCBaBBKJFTt9acwcOmjuVjzzq6TUR0Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T02:34:30Z"
    mac: ENC[AES256_GCM,data:mzMfd+4cpx6T4YMY06jG9mux/qBwvegfyf7Aefca/tOrwg47GdcjvFmxWUFPZw0pk9A5Tjqg4uQSjfN9DzEcu6Vlf7rfonPNvuWeMBl66NRaEkYcOddWCAkLP2bX0nSpRD72hmu12vtw0eAGQ1pXaWkfTvuG9ZiOg+ddpVUFI20=,iv:tIsDthVHLajCLA3zAXflJoOiC3mtgFiROlI+0kkEZmM=,tag:EYTtMc0iKXgmO7lL9/oM3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: memos-app-secrets
    namespace: memos
type: Opaque
stringData:
    MEMOS_DSN: ENC[AES256_GCM,data:SUTlU0d4amKbvOlUlKKkCpyUEjPR+X2o1TlPR5azx5eSRjsnoIsZFG51LYmhWlvnZtxIalJw2xrc/NmQwA0SfXVF25c0Em/4WVOpWahc2WKUFt2Px2AfA4apf3sjx15FGgdynxdJJQ==,iv:t/SdNL74PA3dkatrY0Sb74RCdjLrPsxP5gmwUlcThaI=,tag:CUC2iOo/rX9QNkRwf7uRAg==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOXQvQmExamwvU1U1TXFJ
            YXI2RHlzV1ZoazZ1aEJ2czFpYUwwUWFqU1cwCkZ4TThWY3ltellhZTQzKzZQV2Ro
            RlV0S2hHL3JEUjhaR3lGMHJwUWphVVkKLS0tIHB0MWxYdENseDJoTFVRTXc4V0ll
            OEtlcngybUo1aEJGR3pEVGIrU2RaMHMKzNYlu4bbfqWx8yJ1nQhWJ+e83NduaLWQ
            d/5z/tyq9wjBQGkfp2iSYviCBaBBKJFTt9acwcOmjuVjzzq6TUR0Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T02:34:30Z"
    mac: ENC[AES256_GCM,data:mzMfd+4cpx6T4YMY06jG9mux/qBwvegfyf7Aefca/tOrwg47GdcjvFmxWUFPZw0pk9A5Tjqg4uQSjfN9DzEcu6Vlf7rfonPNvuWeMBl66NRaEkYcOddWCAkLP2bX0nSpRD72hmu12vtw0eAGQ1pXaWkfTvuG9ZiOg+ddpVUFI20=,iv:tIsDthVHLajCLA3zAXflJoOiC3mtgFiROlI+0kkEZmM=,tag:EYTtMc0iKXgmO7lL9/oM3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
