apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beeslab-me-wildcard
  namespace: traefik
spec:
  secretName: beeslab-me-wildcard-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - beeslab.me
    - "*.beeslab.me"
