apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:wJidiMJBAWW33iXmRGtsZSoE7nbhEN/tMhl4VMEmIbMBD3O6eZhxPtTkjXaNNAKjewKzL0o=,iv:0Aof5DcXEGw+b+v8ykRUwqx9JMjnJXrV4r7n56mlwBA=,tag:uxQKJW96+1wGFdkEKTYhfQ==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEVObzlCSTU0SndRNUtP
            SzBDcDhmdHE1cmVaRW1ZUDc5L0g2S3RZcENRClp6amhQK2FMRHBsWnRQOXViRVFr
            eG8wajc4VGVCSGpnNXZsYUl1RlJoekUKLS0tIC9BaWwwMjZyZGE1OHFROE9zRXJZ
            TTVDakFWUFFzYjNnYjZoN1ZyS1hkdE0Kce+Lb+nbc9C8zvXsqp9ds7UNKGh5o0x4
            2EHZWKjTqN1lT0rchZOMMk/IJEXi4grEOVnaHI2EBOHa00sv5zJfOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T18:04:29Z"
    mac: ENC[AES256_GCM,data:P+hlMpxgC4R+WzkdtbNbuk78pzSJDyY28+M7MtfJHd2Nt5roYrMgzNLHK3StSiVEiGr721TrMAX/67y/YSVEa30hlXTwhC88wkUQKkfLy6RpJoTm1GfEl2qObzmw6Ff7GIxWb17hgfCmlPByAN2rIsKFXItiyD/beu1K5Ur9zBU=,iv:p1FJtRs5PBU6DcPNRtt88Ypji4SwDaVgl6WsFdVb+J8=,tag:RDp0b2t4qoNimQ7kXKhKYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
