apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-postgres
  namespace: zitadel
spec:
  instances: 1
  enableSuperuserAccess: true 
  storage:
    size: 3Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
      secret:
        name: zitadel-postgres-owner
