apiVersion: v1
kind: Secret
metadata:
    name: zitadel-postgres-owner
    namespace: zitadel
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:35rKldOptQ==,iv:uN3+jpQYUg6d3fiXptv1+h0dclE/tSlMPl7IrJKL0lM=,tag:i9x+aZihtJamiUlbo8bvXg==,type:str]
    password: ENC[AES256_GCM,data:uEdKHlIOv3wRWJZD/WoJ,iv:ZfPAE3GvYn7O9J2ArPGpig0avVw39uV2beYNmCPY/aE=,tag:0nZGgkBtbacQDnBvw+15Pg==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SXczcEY0dS92a0l1ckla
            eVlEci9xc3MvS21oTlBUMWhrbUFsQzM4eWpnCmIvT205WHdqUlR5MkhRbEpObEM0
            V2pCVWRDZURkeUxMcmJNZWNORTArc1UKLS0tIFVPN1E4MDZRSGVJZEV0L3NhTG11
            U2d0NHNXaVhvaDkwNVE5aG8zNlVQTFEKnTOnGbyoIVH8Tu5PsnshRZCjKbnzqRz7
            RFdWk8pI0f9sa4Sn8MpkCZbYdTzHHc01JBy1V4okP7sWU1HLbA9WQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T02:24:31Z"
    mac: ENC[AES256_GCM,data:0ELW7Tj1+G0a8kw69A0QKobj5+CnjarJKMaJ7OGakU+HtKrMgmOg+4mHSTjjv4xp94Wnwds7zZ6TuZDFazjKfTvX/D8U/bjixiuwvc3tiZ9kRYwPY6fal8Yf5PCwL8ZOhEhioYuooesf7jqlKki6DfjWh+Le7NCHxE6zzzARaq0=,iv:7ZsLmtiAOUu8YIHNFN00jFAImdkbOMiKtmS/xe3U/As=,tag:S+QIwUxJcgm1D53o0/kgWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-values
    namespace: zitadel
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:a1GRjB6sGQMAHGEfIdyutj2+gA4MBkC7uNq2sJequiouXuduVYyy1TrIEzRtefr9DBIYjeJIPs47p2Vk+UuZcsIj8YsNTH5SNjdrlH1SCdQXzvMWdrpPKJ8yksQnOUBYSHbOrSOOJOfagJLVF2Tc5nZuZoVE3YLe6u/WG1F93OOfeEACVLKpGbVMoFLudFNsRGn/9qR2fYJpSB4n1dic5ZvsZsVUjLsLcinEoVwifzwp1rEt8+Sp2NLfc3hC8Lvx2nVkuPEsBurpj8KKJHWq,iv:KMKYY29dZ9RwdrrIa1NBsUcXqI2k1IdkYdpPsg2b7oQ=,tag:kfTzGBqMPpEfZcCSub7xQQ==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SXczcEY0dS92a0l1ckla
            eVlEci9xc3MvS21oTlBUMWhrbUFsQzM4eWpnCmIvT205WHdqUlR5MkhRbEpObEM0
            V2pCVWRDZURkeUxMcmJNZWNORTArc1UKLS0tIFVPN1E4MDZRSGVJZEV0L3NhTG11
            U2d0NHNXaVhvaDkwNVE5aG8zNlVQTFEKnTOnGbyoIVH8Tu5PsnshRZCjKbnzqRz7
            RFdWk8pI0f9sa4Sn8MpkCZbYdTzHHc01JBy1V4okP7sWU1HLbA9WQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T02:24:31Z"
    mac: ENC[AES256_GCM,data:0ELW7Tj1+G0a8kw69A0QKobj5+CnjarJKMaJ7OGakU+HtKrMgmOg+4mHSTjjv4xp94Wnwds7zZ6TuZDFazjKfTvX/D8U/bjixiuwvc3tiZ9kRYwPY6fal8Yf5PCwL8ZOhEhioYuooesf7jqlKki6DfjWh+Le7NCHxE6zzzARaq0=,iv:7ZsLmtiAOUu8YIHNFN00jFAImdkbOMiKtmS/xe3U/As=,tag:S+QIwUxJcgm1D53o0/kgWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
