apiVersion: v1
kind: Secret
metadata:
    name: zitadel-postgres-owner
    namespace: zitadel
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IMb5Qicmqw==,iv:g0sdC/jkWx6Ft6U5rj7xBR46okG6XBwQcwyEp3kYSFo=,tag:o7bc2PoUz19adJxKdQdTbQ==,type:str]
    password: ENC[AES256_GCM,data:mP+j/EutCF9h3G5+W08g,iv:Q2RFBm0jNp1zsUFgz5PUA1aSxbOvb52ybXM219VT+II=,tag:CTI7O9WCUNPGIOVeD7UZKg==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVWFJdHFCSGdQRE9pajFM
            SG1ERFllSGpURElPUjIyUEhrbENHTjZuWmw0CmJlclhQc3gvMEQyb21aM25WZ1RF
            SXBwamhZMlJldS92aDZLNnZVWXpEYXMKLS0tIFBjRy9zeWtJS25QWVJOS1lYMmgw
            b0tQeURETnBxVHN2aERyNXhkY3ZoZEkKqPyetODRP1sQtCQbgCvwRPxvEnuyl7Xm
            O4isBProP0qDGptKCB1e0BynAAVZW61gsEo1M8HYG864AO4FHDwiMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T02:58:03Z"
    mac: ENC[AES256_GCM,data:EYsqB04eBWYdDHLBXaevxrBNXhf4BIijF9XfMTTmc2R/QxvYVy1iVQeF1r5IoD4uZrCRR6elc3Y+iBR44mRkNxwWBapH+nCSx6+V7h2CYI9rh80wbBKRDCyBvsycHC59PV5yJawTMRrX8DYDbrVZasluNSKlDegm7hAN3QjLQRI=,iv:QVBsrYcup2JNTzU6nSkfi7G2NuIg5sZm96vRYtjxYc0=,tag:AnLrHJRj1dJ/iGAyc4E9zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-values
    namespace: zitadel
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ixO+K3oHzFwr9gkBRhXzPyjg21WT9L1c0XmzXXx2R9i4McdGtVhyhaybNWeViz9/rfglKyRTxFJu1B17yo/tTAp8SkBK3F7M1uU4c3ygf5g60NC6l1v4cCRBqniUe3R5B/fWGepoVtAoSj+1usJZ0Nl3GlSPzJzt8X4sjOsUaLx9cz0H4LU1t02Y4gddwzR//sNFq1NQBhUdBtqgWEikU1ae8VRf8sgKTPVxNWoQt6f9MMpRk/cwUNVEMDZCwHE28BT1C4XZ5jVjR+K73Yb625sG+u82Q4IaG3zFSptAaa9Cprz6Ro4dKS4TdnnhElPQ7w0j9/CoKxiPlOTuTWRFTA==,iv:NFJQ6piG7sEqtTay+Ef5mjLg0IWOn34Q6z3b8UqkqsM=,tag:IZDc+dyCYqXjm5ourX6m2Q==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVWFJdHFCSGdQRE9pajFM
            SG1ERFllSGpURElPUjIyUEhrbENHTjZuWmw0CmJlclhQc3gvMEQyb21aM25WZ1RF
            SXBwamhZMlJldS92aDZLNnZVWXpEYXMKLS0tIFBjRy9zeWtJS25QWVJOS1lYMmgw
            b0tQeURETnBxVHN2aERyNXhkY3ZoZEkKqPyetODRP1sQtCQbgCvwRPxvEnuyl7Xm
            O4isBProP0qDGptKCB1e0BynAAVZW61gsEo1M8HYG864AO4FHDwiMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T02:58:03Z"
    mac: ENC[AES256_GCM,data:EYsqB04eBWYdDHLBXaevxrBNXhf4BIijF9XfMTTmc2R/QxvYVy1iVQeF1r5IoD4uZrCRR6elc3Y+iBR44mRkNxwWBapH+nCSx6+V7h2CYI9rh80wbBKRDCyBvsycHC59PV5yJawTMRrX8DYDbrVZasluNSKlDegm7hAN3QjLQRI=,iv:QVBsrYcup2JNTzU6nSkfi7G2NuIg5sZm96vRYtjxYc0=,tag:AnLrHJRj1dJ/iGAyc4E9zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
