apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-values
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:aTd6yps2w/4Z9WDBQAmRdWPU9fHCqknwwHHioCtHrCTuCQjjotDSib2/v/Vn1qerYm32OpEaD/PI+dD5RlDF+aBt1TigP+qUle2Tk78uca4z4VaHC0sIA+yS0HmzaeM7SZz7fmiBv00HI/dWfySh+8sK1HUfhzYGi1M3HsYyqgzKfFu8e46n7lgiHG43bxAjKnhmeT/cfeHHUF6/uAiC+a0jLLcF6D4Gq+eHGWKdHjCVZY13MTafQqj+2HgnPGcG4O3Yxm6yL8ieMhtKjeD+VaDrhca8,iv:fTeXdkq96XToiEU6LM/eBYrqs98BWZDjGhZ9S0fWmUs=,tag:JJK+Jrws4sCvwG4UpedR8w==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRmVzMkZpWXVRTkw0K1l6
            NUs4eVlNQVV2ZTI5WWxRYkVEdlpEbUF4Q0E0CkdZM05wTnNrbXFybjlxK3hvbE5p
            ZmFVSFc5Q01aODlOQzlOekw5ZXRKYzQKLS0tIDl0NFpCUGJiQ0ZzVlhhM3dmVm9J
            M2FSOEFRRm80SlZBanJuTWhCMWRpMjgKrNiYs9d/C0/X2ymI2/1r5P/2eD2U+W++
            U418UbQVB3RiOc7J5aVFXXIL9209j6lKsG8E9xGJ1KJJ5f30P2FETg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T04:36:05Z"
    mac: ENC[AES256_GCM,data:fHrAKYtFsZ8XT970OFl++b5dwpAlm/Bc+LqjfnMjtVPAG5aj4P8jGRw4J2oOMHc1i8L8+oM8D5sGqv9313gn1dN0YANekWuowSO5namD+PqIVoN36mQYZh6LUcvRZXDX8v3MyDja63aBIyPjoiQeH/SbOkZN77e0QzCBZEI1Bpc=,iv:npSMSSUFrALQfgLduYtfPHtyNsfhS6lMpAiC4a7uORA=,tag:Z25h6WLvhxy8qTD7e666UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
