apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-values
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:XNgOHTxPnNnz7ZJVmkkX8md8+J6jhAE2m7/wxZWvtl118v/DO5yxSJQmh4DQ4jaJULNf79KXGnoHa+j04ihaZjiqvOUqSJOpnuwNl9I4F0P3xjEUCP+8Mv+MLmF2svfbKsWksK1q4ojLM8NAUCIy/Sw3mZK69b4bPofkKuGBXJfUrTarGtu7TxvbOb3wGNw82HtEhKSkPK0p9vtUCSDRh0ynNza739vrDIt36+O5eXxstg/7zOIa/+50KhWXrr2JARNYlXRDQfY8PkNWcyP3niQjEiWp,iv:WihrG4KKmK8tr+mEKBCWxo1Rg0yeOLwFS8EY8EyHxvs=,tag:Wh0BX/5tVKvxs0bFm/eeiQ==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRmVzMkZpWXVRTkw0K1l6
            NUs4eVlNQVV2ZTI5WWxRYkVEdlpEbUF4Q0E0CkdZM05wTnNrbXFybjlxK3hvbE5p
            ZmFVSFc5Q01aODlOQzlOekw5ZXRKYzQKLS0tIDl0NFpCUGJiQ0ZzVlhhM3dmVm9J
            M2FSOEFRRm80SlZBanJuTWhCMWRpMjgKrNiYs9d/C0/X2ymI2/1r5P/2eD2U+W++
            U418UbQVB3RiOc7J5aVFXXIL9209j6lKsG8E9xGJ1KJJ5f30P2FETg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T00:08:24Z"
    mac: ENC[AES256_GCM,data:n9xD8rTdzIiqpVF88SnQAVs++Q3TsV6XlGkLAKWDQ3NkUSZU9pH/4pFA3qRhDrVtkbv86GgIHF5QRbq7VakBwmR/ueEuN8FkoN5nVXlSnCy8F1rAdCWHoxQfoHSWbvM5sF2m4EE72Vbv6VD/3ZNuXEmqVb7ghJnm0/PN06Zh524=,iv:9Z3+Rd8EeJlaKeWu19zYIVfesNh0xwMM0VkbfYRkn/E=,tag:ZVaaWtnRMo7thWE5D8z/5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
