apiVersion: v1
kind: Secret
metadata:
    name: miniflux-postgres-owner
    namespace: miniflux
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:c1voOuHaxJ4=,iv:OGaRh1NwcZFPqR9RxDmD0ssB82RR7/LFB9tWe9Q5Ig8=,tag:2nkBcxSXu/BoDh82YLrVJA==,type:str]
    password: ENC[AES256_GCM,data:k8kupAyYAu5o3iN2Aeo4Wg==,iv:Bo/qX/H7PQtKhBAhQzpeaupXGw/lsby8dPH/n4doz24=,tag:HhE8I/wPE4DP/RgtCzYoLg==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b0kyaTNHSE9jNStIQklB
            TVBrcENFS0JlSndldE5jTGY1dkhoRHBYaEQwCjhpczNTcEt6OVp5NTRHd2FtZlZl
            aWdySWZQYzl6K25HOEZrRW1zZFJoc0UKLS0tIEYza0trMmlSaGZycXg4VUpPN20v
            Ky91Z0xVeGtyeDl6d21BQkhPOHF5eUEKPv23rC4p4ZPvRaUATYul3ROA6sPvnnP5
            9IY1nrH7P2Vm52SwXeKwr3XPXcDiGagrgT2YgPshzhtwtxDfWyNbhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:49:51Z"
    mac: ENC[AES256_GCM,data:kgU2rqMG/oif6y4hnFynzCyjiZpLhrt3N1vDaPXTEO2bLz1yVjnC2LY1oqrCUzHvAIyoXwPRROrBPHOETzjC/PVLMYhfjeb+kmbBfRbXC8cyhPi4JcFtY5GgB1irilRTWJkqRRCCAfwrQTxC9S8fv1Eh0XxYpu1Op3U4YsJW6b8=,iv:3PoTL8AGw88QhDRVM273WWpdjDnK6VCUKeQ+G38dans=,tag:ZWzt4Dn7gfDQ+tr3MFFxLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-app-secrets
    namespace: miniflux
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ciKNvFiFon5T5upUbxptk8XyCJc+trViohmI7kTKoAiFC/ikY6NfBBtPwQAwNpUbHyaKxZOAiAbXUm94JVRZZ/IjlsvyByy7TG/EiO+5j0AT9Y0B/iYH11OewvxFQ/GeF671WLVn,iv:adD+FwnzqdokeebAlSg3phhJeqtiIMikDhi6+0QtC/g=,tag:d7clnCNJl2CYZXdOc82soQ==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:pA7BNfI=,iv:z+nYFgjXM14Hp7UTZK7BOowHrbkTCdeGM7+ekIplp/A=,tag:Fhab+aLx1nbAlRifLcMGtA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:l89gN8W99x2WxZtWAsqx2w==,iv:wcIoVyiBIlXEuS6jWM3WCZ51iK3KqF4NjRath3MyNkY=,tag:sdFbD2uhfNGSw0yIGPT3CA==,type:str]
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:KuXvcxAXdp+Lb0dEUvHgjh+R,iv:bzNjMnYM/Efg4rQNgkKyjA4JSer+vP7+Ci1j8VjkTFM=,tag:qWeHBIkeew6p0iahQM4zGQ==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:hczrzlb3dDeVv6edJYwycnsTduEFx3ZTLgxX7BW96F1j3aiUcizwdWGmjP6KwHUnmhIksqRmmiMEr0s7dJ8eGQ==,iv:uFf0PJTTbHgEccpGxEqzmVg5DEC7fxKWxCT4np3fkbo=,tag:/Fk8+IoHSz4AxYwSpVGIwg==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b0kyaTNHSE9jNStIQklB
            TVBrcENFS0JlSndldE5jTGY1dkhoRHBYaEQwCjhpczNTcEt6OVp5NTRHd2FtZlZl
            aWdySWZQYzl6K25HOEZrRW1zZFJoc0UKLS0tIEYza0trMmlSaGZycXg4VUpPN20v
            Ky91Z0xVeGtyeDl6d21BQkhPOHF5eUEKPv23rC4p4ZPvRaUATYul3ROA6sPvnnP5
            9IY1nrH7P2Vm52SwXeKwr3XPXcDiGagrgT2YgPshzhtwtxDfWyNbhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:49:51Z"
    mac: ENC[AES256_GCM,data:kgU2rqMG/oif6y4hnFynzCyjiZpLhrt3N1vDaPXTEO2bLz1yVjnC2LY1oqrCUzHvAIyoXwPRROrBPHOETzjC/PVLMYhfjeb+kmbBfRbXC8cyhPi4JcFtY5GgB1irilRTWJkqRRCCAfwrQTxC9S8fv1Eh0XxYpu1Op3U4YsJW6b8=,iv:3PoTL8AGw88QhDRVM273WWpdjDnK6VCUKeQ+G38dans=,tag:ZWzt4Dn7gfDQ+tr3MFFxLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
