apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zitadel
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/auth/zitadel/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn
    - name: cnpg
