apiVersion: v1
kind: Secret
metadata:
    name: actualbudget-app-secrets
    namespace: actualbudget
type: Opaque
stringData:
    ACTUAL_OPENID_DISCOVERY_URL: ENC[AES256_GCM,data:dGYaMY5CsDkRDj5fBUkCQDuah3Y/8jjdTHEJJiPGYw6uirKOAjE2VHRkUNlh6oMZdMN3GZytSVRC+fo=,iv:KfFyInNbG3QVjNF2ZB0enZoyFXVaOJZ160b0cF7Pd90=,tag:0A/KEHdFRJk8oCONyVUmaA==,type:str]
    ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:3JsAsY8Wt4wAa+eddSf0bDjL,iv:/HdMd5t2fnP5L3EbWQBeq3aHkMlCJzSJZe3xKjUY3E0=,tag:ZgF8CdCkQswB7BCkYPQZDA==,type:int]
    ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:T6dFp1kb4EjcTgQ8dF1bB4COU2pihi6y9t5JyCOKYpOGUAdIQxi15aYzU6A1gd/UfpvBM14FLIzqn7lA7Cccog==,iv:DiVY/kF2ewyobyllhJs7bbT3238pQihWw+Ohh6RQ1dw=,tag:rgevbYY+PQZ2l9/KDthCyg==,type:str]
    ACTUAL_OPENID_SERVER_HOSTNAME: ENC[AES256_GCM,data:FEJ/TYpX4LGX7ymnn4f9zYHJYj3NBGRwOg==,iv:OJItvJKyMbFGQQXJksH7i0eFdnp+f1UDA2vThlpmPEo=,tag:y6DopsG22Qfnqjy2B9kBVw==,type:str]
    ACTUAL_OPENID_ENFORCE: ENC[AES256_GCM,data:4DF4YQ==,iv:ZWvyD8dsSFakvJ8i6fMGDVuTX7Xk08pVCi0+3sZ88Wg=,tag:GyRXsLjiUYqiIoA1hn2HWA==,type:bool]
    ACTUAL_USER_CREATION_MODE: ENC[AES256_GCM,data:RUO/1E0=,iv:o0OUlPP/duTeOIH1Tac0i3A+9J8okMnhV/MEz/b/Nbw=,tag:LODMODYJUdCdTt4wqPPMHw==,type:str]
sops:
    age:
        - recipient: age1mdmmlcdnqclygnffmxcr07v58aj4mex2huk70e4nwvqa2gtkdgesge8rzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdExKZnhER2dqSnFNZThT
            NVFlNHUrYkc4eTR0N29GT1l2SXkzVE9ONndJCkxGbHNpeEcwTHdlT2tXdHkydFV6
            N0lCd2NBYkRxS1B1VVUxdWJ4K1BrK3MKLS0tIFVROGUrTGF4dXFLandEMEZRY1pK
            RGNFcjNqTFJEVldkVXpwVXJLSHdoYXcKCXweG3bhWUd/QoNGJ830o0Ymljjv8yjQ
            HSF9DHdZQnScwwsTbBXPWIT8rKzj9wPmBl4pSZ/WQXDPvHhnaxfXVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T17:33:01Z"
    mac: ENC[AES256_GCM,data:KElZChVNrNVZWomiU+Zf12miton6uSnF/BhQ8gWyB2Q1NMV7mhBmae95oQ87ykUOSi3MmoeHY5TYBeEIYRJpw7IUeMxaR1aFvewmkO3xfTP7Pd9nXphBPyEQ68hwojHBWwMGDWGRPc5avcLF17nGyclQ1pdL1eqQO83QnNwoohc=,iv:sZSLx+bzu/CSQWUut0dGNNBwlwiG5RRu73stCh+3NQE=,tag:DDbB+6Vi540AgGTF7JEUnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
